
# Automatic semantic version releases
#
# Check https://github.com/python-semantic-release/python-semantic-release
# Look here to see which commit message leads to which release type
# https://github.com/semantic-release/semantic-release?tab=readme-ov-file#commit-message-format
#

name: Semantic Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
